# Generated by Django 5.1.4 on 2025-01-19 22:18

import flashie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=flashie.models.audio_upload_path),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='pdf',
            field=models.FileField(upload_to=flashie.models.pdf_upload_path),
        ),
    ]
