# Generated by Django 5.1.4 on 2025-01-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashie', '0004_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='presentation',
            field=models.FileField(help_text='Accepted formats: PDF, PPT, PPTX', upload_to='lectures/presentations/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='script',
            field=models.FileField(help_text='Accepted formats: PDF, TXT, DOC, DOCX', upload_to='lectures/scripts/'),
        ),
    ]
