# Generated by Django 5.1.4 on 2025-01-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashie', '0005_alter_lecture_presentation_alter_lecture_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='processed_script',
            field=models.TextField(blank=True),
        ),
    ]
