# Generated by Django 5.1.4 on 2025-01-28 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashie', '0006_lecture_processed_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='flashie.lecture')),
            ],
            options={
                'ordering': ['slide_number'],
            },
        ),
    ]
