# Generated by Django 5.1.4 on 2025-01-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashie', '0007_lectureslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureslide',
            name='annotation',
            field=models.TextField(blank=True),
        ),
    ]
