# Generated by Django 5.1.4 on 2025-02-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashie', '0002_add_title_to_lectureslide'),
        ('flashie', '0008_lectureslide_annotation'),
    ]

    operations = [
    ]
